### ISSUE TITLE
서비스레이어 간에 순환 의존 관계 Or 양방향 의존관 관계 문제

### ISSUE THREAD

**Issue by songhaechan** [Project-Linking/back-end#21]
## Discussion

서비스 레이어 사이에서 직접 서로의 서비스를 객체 탐색으로 의존하는 경우

순환의존이나 양방향의존이 발생할 수 있는데 이 의존성을 느슨하게 가져갈 수 있는 방법을 고민해보고싶습니다.

예를 들어 아래와 같은 상황입니다.

```java
@RequiredArgsContstructor
public class BoardService{
    private final CommentService commentService;
}

@RequiredArgsContstructor
public class CommentService{
    private final BoardService boardService;
}
```

제 생각엔 스프링이 제공하는 이벤트리스너를 사용하면 결합도를 낮출 수 있을 것 같은데

더 좋은 방법이 있으시면 코멘트 부탁드립니다.

**Comment by SangWoon123** [comment]
제가 예상으로는 Service 코드에서 DB에 접근하는 로직이 포함되어있던게 고민이 맞을까요? 

### 문제

``` java
// CommentService 정의
@Transactional(readOnly = true)
@Service
@RequiredArgsConstructor
public class CommentService {

    private final BoardService boardService;

    public Comment getCommentById(Long commentId) {
        return commentRepository.findById(commentId)
                .orElseThrow(() -> new CommentException(CommentErrorCode.COMMENT_NOT_FOUND.changeDefaultDescription("댓글이 존재하지 않습니다.")));
    }
}

// BoardService 정의
@Transactional(readOnly = true)
@Service
@RequiredArgsConstructor
public class BoardService {

    private final CommentService commentService;

    public void b() {
        commentService.getCommentById(); 
    }
}

```

위 코드에서는 CommentService 내부에서 BoardService를 호출하고 BoardService 내부에서는 CommentService를 다시 호출하는 순환 의존 구조가 나타나는데, 이러한 구조는 시스템의 복잡성을 증가시키고 유지 보수를 어렵게 만듭니다

만약 위 경우가 맞다면

### 해결 방안: CommentQueryService의 도입 제안

현재 간단한 방법으로는 CommentService 클래스에 정의 되어있는 일부 기능을 여러 Service 클래스로 분리하는 것이 간단한 방법같습니다.

클린코드에서도 작은 클래스 여럿으로 이룬 시스템이 더 바람직하다라는 얘기가 있습니다.

 ex) CommentService getCommentById를 CommentQueryService로 분리하여 관리하는 것이 클래스 역할 분산과함께 순환문젤 해결하고, 서비스 클래스 책임 분리 관점에서 나아 보이는데 어떤가요?

```java

@Service
@RequiredArgsConstructor
public class CommentQueryService {

    private final CommentRepository commentRepository;

    public Comment getCommentById(Long commentId) {
        return commentRepository.findById(commentId)
                .orElseThrow(() -> new CommentException(CommentErrorCode.COMMENT_NOT_FOUND.changeDefaultDescription("댓글이 존재하지 않습니다.")));
    }
}

```

이벤트 리스너 방식과 비교했을때 어떨지 알려주시면 감사하겠습니다.

**Comment by songhaechan** [comment]
상운님이 제시해주신 방식에 대해 공부를 좀 해봤습니다.
서비스레이어 자체를 하나는 고수준(비지니스 로직에 집중) 하나는 저수준(단순 조회에 집중)하는 방식으로 쪼개서 구현하고
파사드 레이어 패턴으로 이해했습니다. (혹시 제가 이해한게 틀리다면 말씀해주세요!)

책임 분리 측면에서도 의존방향을 단방향으로 흐르게한다는 면에서도(현재 저희가 채택한 패키지 구조라면 패키지 순환이 발생할 순 있을 거라 생각합니다.) 좋은 방법이라 생각됩니다! 많이 배웠습니다 ㅎㅎ

공부를 하다보니 지금 저희 상황은 그리 복잡한 서비스 로직을 가진 메서드를 다른 서비스레이어가 사용해야하는 일은 없다고 생각됩니다.
그래서 현 상황에서 순환의존이나 양방향 의존이 걸렸다면 상운님이 말씀해주신 방향으로 가는게 좋다고 생각합니다.

다만 **복잡한 서비스 로직**을 불러와서 처리해야하는 경우에는 QueryService만을 사용할 수는 없으니 서비스 레이어를 의존해야할 텐데
이 의존성을 낮추는 방식이 스프링의 이벤트리스너입니다.
보통 비동기+이벤트 발행/구독 , 동기+이벤트 발행/구독 방식으로 많이 사용하고 트랜잭션 범위까지 지정해줄 수 있는 좋은 기술인것 같습니다.

 그런데 지금 상황에서 그다지 복잡한 로직을 다른 서비스레이어가 호출할 일은 없다고 판단돼서 이벤트리스너까지 도입하는건 현 상황에서는 오버엔지니어링 같다고 생각합니다!
